id: A9BD5F36C
title: Toh_340-The_Hundred_Deeds-v2
type: translation
pechas:
- I2E118D9E
- I5C428F78
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-073-001
  eft-text-version: 1.2.2 2020
  title: Toh_340-The_Hundred_Deeds-v2
alignment_to_base:
  I2E118D9E/64E0: B4CE
  I5C428F78/A629: B4CE
